package com.yabobaozb.ecom.payment.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.pay_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.amount
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.pay_type
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private Short payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.source_order_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private Long sourceOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.remark
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.create_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_info.update_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.pay_id
     *
     * @return the value of payment_info.pay_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.pay_id
     *
     * @param payId the value for payment_info.pay_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.amount
     *
     * @return the value of payment_info.amount
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.amount
     *
     * @param amount the value for payment_info.amount
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.pay_type
     *
     * @return the value of payment_info.pay_type
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.pay_type
     *
     * @param payType the value for payment_info.pay_type
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.source_order_id
     *
     * @return the value of payment_info.source_order_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public Long getSourceOrderId() {
        return sourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.source_order_id
     *
     * @param sourceOrderId the value for payment_info.source_order_id
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setSourceOrderId(Long sourceOrderId) {
        this.sourceOrderId = sourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.remark
     *
     * @return the value of payment_info.remark
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.remark
     *
     * @param remark the value for payment_info.remark
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.create_time
     *
     * @return the value of payment_info.create_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.create_time
     *
     * @param createTime the value for payment_info.create_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_info.update_time
     *
     * @return the value of payment_info.update_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_info.update_time
     *
     * @param updateTime the value for payment_info.update_time
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}