package com.yabobaozb.ecom.payment.infra.mapper;

import com.yabobaozb.ecom.payment.infra.model.PaymentInfoDO;

public interface PaymentInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    int deleteByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    int insert(PaymentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    int insertSelective(PaymentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    PaymentInfoDO selectByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    int updateByPrimaryKeySelective(PaymentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_info
     *
     * @mbg.generated Wed Jun 18 10:42:11 CST 2025
     */
    int updateByPrimaryKey(PaymentInfoDO record);
}