package com.yabobaozb.ecom.commodity.infra.mapper;

import com.yabobaozb.ecom.commodity.infra.model.SkuInventoryRecordDO;

public interface SkuInventoryRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    int insert(SkuInventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    int insertSelective(SkuInventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    SkuInventoryRecordDO selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    int updateByPrimaryKeySelective(SkuInventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_inventory_record
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    int updateByPrimaryKey(SkuInventoryRecordDO record);
}