package com.yabobaozb.ecom.commodity.infra.mapper;

import com.yabobaozb.ecom.commodity.infra.model.SkuInfoDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SkuInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    int deleteByPrimaryKey(Long skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    int insert(SkuInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    int insertSelective(SkuInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    SkuInfoDO selectByPrimaryKey(Long skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    int updateByPrimaryKeySelective(SkuInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_info
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    int updateByPrimaryKey(SkuInfoDO record);

    List<SkuInfoDO> selectBySkuIds(@Param("merchantId")long merchantId, @Param("skuIdList") List<Long> skuIdList);
}