package com.yabobaozb.ecom.order.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_payable
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private BigDecimal amountPayable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount_paid
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private BigDecimal amountPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sku_size
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Integer skuSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_quantity
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Integer totalQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_result
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Short payResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyer_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_payable
     *
     * @return the value of order_info.amount_payable
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public BigDecimal getAmountPayable() {
        return amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_payable
     *
     * @param amountPayable the value for order_info.amount_payable
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setAmountPayable(BigDecimal amountPayable) {
        this.amountPayable = amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount_paid
     *
     * @return the value of order_info.amount_paid
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public BigDecimal getAmountPaid() {
        return amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount_paid
     *
     * @param amountPaid the value for order_info.amount_paid
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sku_size
     *
     * @return the value of order_info.sku_size
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Integer getSkuSize() {
        return skuSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sku_size
     *
     * @param skuSize the value for order_info.sku_size
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setSkuSize(Integer skuSize) {
        this.skuSize = skuSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_quantity
     *
     * @return the value of order_info.total_quantity
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_quantity
     *
     * @param totalQuantity the value for order_info.total_quantity
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_result
     *
     * @return the value of order_info.pay_result
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Short getPayResult() {
        return payResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_result
     *
     * @param payResult the value for order_info.pay_result
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setPayResult(Short payResult) {
        this.payResult = payResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order_info.order_status
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyer_id
     *
     * @return the value of order_info.buyer_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyer_id
     *
     * @param buyerId the value for order_info.buyer_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_id
     *
     * @return the value of order_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_id
     *
     * @param merchantId the value for order_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}