package com.yabobaozb.ecom.order.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderPaymentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.pay_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.amount
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.pay_type
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Short payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.pay_id
     *
     * @return the value of order_payment.pay_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.pay_id
     *
     * @param payId the value for order_payment.pay_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.order_id
     *
     * @return the value of order_payment.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.order_id
     *
     * @param orderId the value for order_payment.order_id
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.amount
     *
     * @return the value of order_payment.amount
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.amount
     *
     * @param amount the value for order_payment.amount
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.pay_type
     *
     * @return the value of order_payment.pay_type
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.pay_type
     *
     * @param payType the value for order_payment.pay_type
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.create_time
     *
     * @return the value of order_payment.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.create_time
     *
     * @param createTime the value for order_payment.create_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment.update_time
     *
     * @return the value of order_payment.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment.update_time
     *
     * @param updateTime the value for order_payment.update_time
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}