package com.yabobaozb.ecom.merchant.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantBalanceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance.version
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance.merchant_id
     *
     * @return the value of merchant_balance.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance.merchant_id
     *
     * @param merchantId the value for merchant_balance.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance.balance
     *
     * @return the value of merchant_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance.balance
     *
     * @param balance the value for merchant_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance.version
     *
     * @return the value of merchant_balance.version
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance.version
     *
     * @param version the value for merchant_balance.version
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance.create_time
     *
     * @return the value of merchant_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance.create_time
     *
     * @param createTime the value for merchant_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance.update_time
     *
     * @return the value of merchant_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance.update_time
     *
     * @param updateTime the value for merchant_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}