package com.yabobaozb.ecom.merchant.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantBalanceRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.record_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Long recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.change_type
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Short changeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.amount
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.balance_from
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private BigDecimal balanceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.balance_to
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private BigDecimal balanceTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.pay_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.source_order_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Long sourceOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.remark
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.create_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_balance_record.update_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.record_id
     *
     * @return the value of merchant_balance_record.record_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.record_id
     *
     * @param recordId the value for merchant_balance_record.record_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.merchant_id
     *
     * @return the value of merchant_balance_record.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.merchant_id
     *
     * @param merchantId the value for merchant_balance_record.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.change_type
     *
     * @return the value of merchant_balance_record.change_type
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Short getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.change_type
     *
     * @param changeType the value for merchant_balance_record.change_type
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setChangeType(Short changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.amount
     *
     * @return the value of merchant_balance_record.amount
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.amount
     *
     * @param amount the value for merchant_balance_record.amount
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.balance_from
     *
     * @return the value of merchant_balance_record.balance_from
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public BigDecimal getBalanceFrom() {
        return balanceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.balance_from
     *
     * @param balanceFrom the value for merchant_balance_record.balance_from
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setBalanceFrom(BigDecimal balanceFrom) {
        this.balanceFrom = balanceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.balance_to
     *
     * @return the value of merchant_balance_record.balance_to
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public BigDecimal getBalanceTo() {
        return balanceTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.balance_to
     *
     * @param balanceTo the value for merchant_balance_record.balance_to
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setBalanceTo(BigDecimal balanceTo) {
        this.balanceTo = balanceTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.pay_id
     *
     * @return the value of merchant_balance_record.pay_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.pay_id
     *
     * @param payId the value for merchant_balance_record.pay_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.source_order_id
     *
     * @return the value of merchant_balance_record.source_order_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Long getSourceOrderId() {
        return sourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.source_order_id
     *
     * @param sourceOrderId the value for merchant_balance_record.source_order_id
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setSourceOrderId(Long sourceOrderId) {
        this.sourceOrderId = sourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.remark
     *
     * @return the value of merchant_balance_record.remark
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.remark
     *
     * @param remark the value for merchant_balance_record.remark
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.create_time
     *
     * @return the value of merchant_balance_record.create_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.create_time
     *
     * @param createTime the value for merchant_balance_record.create_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_balance_record.update_time
     *
     * @return the value of merchant_balance_record.update_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_balance_record.update_time
     *
     * @param updateTime the value for merchant_balance_record.update_time
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}