package com.yabobaozb.ecom.merchant.infra.model;

import java.util.Date;

public class MerchantInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.name
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.merchant_id
     *
     * @return the value of merchant_info.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.merchant_id
     *
     * @param merchantId the value for merchant_info.merchant_id
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.name
     *
     * @return the value of merchant_info.name
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.name
     *
     * @param name the value for merchant_info.name
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.create_time
     *
     * @return the value of merchant_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.create_time
     *
     * @param createTime the value for merchant_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.update_time
     *
     * @return the value of merchant_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.update_time
     *
     * @param updateTime the value for merchant_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}