package com.yabobaozb.ecom.buyer.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class BuyerBalanceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_balance.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_balance.version
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_balance.buyer_id
     *
     * @return the value of buyer_balance.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_balance.buyer_id
     *
     * @param buyerId the value for buyer_balance.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_balance.balance
     *
     * @return the value of buyer_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_balance.balance
     *
     * @param balance the value for buyer_balance.balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_balance.version
     *
     * @return the value of buyer_balance.version
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_balance.version
     *
     * @param version the value for buyer_balance.version
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_balance.create_time
     *
     * @return the value of buyer_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_balance.create_time
     *
     * @param createTime the value for buyer_balance.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_balance.update_time
     *
     * @return the value of buyer_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_balance.update_time
     *
     * @param updateTime the value for buyer_balance.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}