package com.yabobaozb.ecom.buyer.infra.model;

import java.util.Date;

public class BuyerInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.name
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.buyer_id
     *
     * @return the value of buyer_info.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.buyer_id
     *
     * @param buyerId the value for buyer_info.buyer_id
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.name
     *
     * @return the value of buyer_info.name
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.name
     *
     * @param name the value for buyer_info.name
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.create_time
     *
     * @return the value of buyer_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.create_time
     *
     * @param createTime the value for buyer_info.create_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.update_time
     *
     * @return the value of buyer_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.update_time
     *
     * @param updateTime the value for buyer_info.update_time
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}