package com.yabobaozb.ecom.settlement.infra.mapper;

import com.yabobaozb.ecom.settlement.infra.model.SettlementInfoRecordDO;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface SettlementInfoRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    int insert(SettlementInfoRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    int insertSelective(SettlementInfoRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    SettlementInfoRecordDO selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    int updateByPrimaryKeySelective(SettlementInfoRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_info_record
     *
     * @mbg.generated Sun Jun 22 17:08:30 CST 2025
     */
    int updateByPrimaryKey(SettlementInfoRecordDO record);

    List<SettlementInfoRecordDO> selectByMerchantAndSettleTime(@RequestParam("merchantId") long merchantId, @RequestParam("settleTime") String settleTime);
}