package com.yabobaozb.ecom.buyer.infra.mapper;

import com.yabobaozb.ecom.buyer.infra.model.BuyerBalanceRecordDO;

public interface BuyerBalanceRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insert(BuyerBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insertSelective(BuyerBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    BuyerBalanceRecordDO selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKeySelective(BuyerBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance_record
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKey(BuyerBalanceRecordDO record);
}