package com.yabobaozb.ecom.buyer.infra.mapper;

import com.yabobaozb.ecom.buyer.infra.model.BuyerBalanceDO;
import com.yabobaozb.ecom.buyer.infra.model.BuyerBalanceVersionDO;

public interface BuyerBalanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int deleteByPrimaryKey(Long buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insert(BuyerBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insertSelective(BuyerBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    BuyerBalanceDO selectByPrimaryKey(Long buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKeySelective(BuyerBalanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_balance
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKey(BuyerBalanceDO record);

    int updateBalanceByVersion(BuyerBalanceVersionDO buyerBalanceVersionDO);
}