package com.yabobaozb.ecom.buyer.infra.mapper;

import com.yabobaozb.ecom.buyer.infra.model.BuyerInfoDO;

public interface BuyerInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int deleteByPrimaryKey(Long buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insert(BuyerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int insertSelective(BuyerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    BuyerInfoDO selectByPrimaryKey(Long buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKeySelective(BuyerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbg.generated Thu Jun 19 10:42:30 CST 2025
     */
    int updateByPrimaryKey(BuyerInfoDO record);
}