package com.yabobaozb.ecom.settlement.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class SettlementInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.settle_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private Long settleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.merchant_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.settle_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private String settleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.begin_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private String beginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.end_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private String endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.expect_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private BigDecimal expectAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.settle_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private BigDecimal settleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.diff_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private BigDecimal diffAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.settle_result
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private Short settleResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.remark
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.create_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_info.update_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.settle_id
     *
     * @return the value of settlement_info.settle_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public Long getSettleId() {
        return settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.settle_id
     *
     * @param settleId the value for settlement_info.settle_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setSettleId(Long settleId) {
        this.settleId = settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.merchant_id
     *
     * @return the value of settlement_info.merchant_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.merchant_id
     *
     * @param merchantId the value for settlement_info.merchant_id
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.settle_time
     *
     * @return the value of settlement_info.settle_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public String getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.settle_time
     *
     * @param settleTime the value for settlement_info.settle_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setSettleTime(String settleTime) {
        this.settleTime = settleTime == null ? null : settleTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.begin_at
     *
     * @return the value of settlement_info.begin_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public String getBeginAt() {
        return beginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.begin_at
     *
     * @param beginAt the value for settlement_info.begin_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setBeginAt(String beginAt) {
        this.beginAt = beginAt == null ? null : beginAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.end_at
     *
     * @return the value of settlement_info.end_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public String getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.end_at
     *
     * @param endAt the value for settlement_info.end_at
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setEndAt(String endAt) {
        this.endAt = endAt == null ? null : endAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.expect_amount
     *
     * @return the value of settlement_info.expect_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public BigDecimal getExpectAmount() {
        return expectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.expect_amount
     *
     * @param expectAmount the value for settlement_info.expect_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setExpectAmount(BigDecimal expectAmount) {
        this.expectAmount = expectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.settle_amount
     *
     * @return the value of settlement_info.settle_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public BigDecimal getSettleAmount() {
        return settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.settle_amount
     *
     * @param settleAmount the value for settlement_info.settle_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setSettleAmount(BigDecimal settleAmount) {
        this.settleAmount = settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.diff_amount
     *
     * @return the value of settlement_info.diff_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public BigDecimal getDiffAmount() {
        return diffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.diff_amount
     *
     * @param diffAmount the value for settlement_info.diff_amount
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setDiffAmount(BigDecimal diffAmount) {
        this.diffAmount = diffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.settle_result
     *
     * @return the value of settlement_info.settle_result
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public Short getSettleResult() {
        return settleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.settle_result
     *
     * @param settleResult the value for settlement_info.settle_result
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setSettleResult(Short settleResult) {
        this.settleResult = settleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.remark
     *
     * @return the value of settlement_info.remark
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.remark
     *
     * @param remark the value for settlement_info.remark
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.create_time
     *
     * @return the value of settlement_info.create_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.create_time
     *
     * @param createTime the value for settlement_info.create_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_info.update_time
     *
     * @return the value of settlement_info.update_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_info.update_time
     *
     * @param updateTime the value for settlement_info.update_time
     *
     * @mbg.generated Sun Jun 22 12:24:23 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}