package com.yabobaozb.ecom.order.infra.mapper;

import com.yabobaozb.ecom.order.infra.model.OrderPaymentDO;

import java.util.List;

public interface OrderPaymentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int deleteByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int insert(OrderPaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int insertSelective(OrderPaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    OrderPaymentDO selectByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int updateByPrimaryKeySelective(OrderPaymentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int updateByPrimaryKey(OrderPaymentDO record);

    List<OrderPaymentDO> selectByOrderId(long orderId);
}