package com.yabobaozb.ecom.order.infra.mapper;

import com.yabobaozb.ecom.order.infra.model.OrderItemDO;

import java.util.List;

public interface OrderItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int insert(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int insertSelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    OrderItemDO selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int updateByPrimaryKeySelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Jun 20 18:17:14 CST 2025
     */
    int updateByPrimaryKey(OrderItemDO record);

    List<OrderItemDO> selectByOrderId(long orderId);
}