package com.yabobaozb.ecom.merchant.infra.mapper;

import com.yabobaozb.ecom.merchant.infra.model.MerchantInfoDO;

public interface MerchantInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    int deleteByPrimaryKey(Long merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    int insert(MerchantInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    int insertSelective(MerchantInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    MerchantInfoDO selectByPrimaryKey(Long merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    int updateByPrimaryKeySelective(MerchantInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Thu Jun 19 10:51:38 CST 2025
     */
    int updateByPrimaryKey(MerchantInfoDO record);
}