package com.yabobaozb.ecom.merchant.infra.mapper;

import com.yabobaozb.ecom.merchant.infra.model.MerchantBalanceRecordDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantBalanceRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    int insert(MerchantBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    int insertSelective(MerchantBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    MerchantBalanceRecordDO selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    int updateByPrimaryKeySelective(MerchantBalanceRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_balance_record
     *
     * @mbg.generated Fri Jun 20 15:21:13 CST 2025
     */
    int updateByPrimaryKey(MerchantBalanceRecordDO record);

    List<MerchantBalanceRecordDO> selectByMerchantId(long merchantId);

    List<MerchantBalanceRecordDO> selectByMerchantAndCreateTime(@Param("merchantId") long merchantId, @Param("beginAt") String beginAt, @Param("endAt") String endAt);
}