package com.yabobaozb.ecom.commodity.infra.model;

import java.util.Date;

public class SkuInventoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory.available_inventory
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Integer availableInventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory.version
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory.sku_id
     *
     * @return the value of sku_inventory.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory.sku_id
     *
     * @param skuId the value for sku_inventory.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory.available_inventory
     *
     * @return the value of sku_inventory.available_inventory
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Integer getAvailableInventory() {
        return availableInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory.available_inventory
     *
     * @param availableInventory the value for sku_inventory.available_inventory
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setAvailableInventory(Integer availableInventory) {
        this.availableInventory = availableInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory.version
     *
     * @return the value of sku_inventory.version
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory.version
     *
     * @param version the value for sku_inventory.version
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory.create_time
     *
     * @return the value of sku_inventory.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory.create_time
     *
     * @param createTime the value for sku_inventory.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory.update_time
     *
     * @return the value of sku_inventory.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory.update_time
     *
     * @param updateTime the value for sku_inventory.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}