package com.yabobaozb.ecom.commodity.infra.model;

import java.util.Date;

public class SkuInventoryRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.record_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.change_type
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Short changeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.quantity
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.inventory_from
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Integer inventoryFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.inventory_to
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Integer inventoryTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.pay_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.soruce_order_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Long soruceOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.remark
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_inventory_record.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.record_id
     *
     * @return the value of sku_inventory_record.record_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.record_id
     *
     * @param recordId the value for sku_inventory_record.record_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.sku_id
     *
     * @return the value of sku_inventory_record.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.sku_id
     *
     * @param skuId the value for sku_inventory_record.sku_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.change_type
     *
     * @return the value of sku_inventory_record.change_type
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Short getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.change_type
     *
     * @param changeType the value for sku_inventory_record.change_type
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setChangeType(Short changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.quantity
     *
     * @return the value of sku_inventory_record.quantity
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.quantity
     *
     * @param quantity the value for sku_inventory_record.quantity
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.inventory_from
     *
     * @return the value of sku_inventory_record.inventory_from
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Integer getInventoryFrom() {
        return inventoryFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.inventory_from
     *
     * @param inventoryFrom the value for sku_inventory_record.inventory_from
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setInventoryFrom(Integer inventoryFrom) {
        this.inventoryFrom = inventoryFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.inventory_to
     *
     * @return the value of sku_inventory_record.inventory_to
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Integer getInventoryTo() {
        return inventoryTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.inventory_to
     *
     * @param inventoryTo the value for sku_inventory_record.inventory_to
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setInventoryTo(Integer inventoryTo) {
        this.inventoryTo = inventoryTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.pay_id
     *
     * @return the value of sku_inventory_record.pay_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.pay_id
     *
     * @param payId the value for sku_inventory_record.pay_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.soruce_order_id
     *
     * @return the value of sku_inventory_record.soruce_order_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Long getSoruceOrderId() {
        return soruceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.soruce_order_id
     *
     * @param soruceOrderId the value for sku_inventory_record.soruce_order_id
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setSoruceOrderId(Long soruceOrderId) {
        this.soruceOrderId = soruceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.remark
     *
     * @return the value of sku_inventory_record.remark
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.remark
     *
     * @param remark the value for sku_inventory_record.remark
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.create_time
     *
     * @return the value of sku_inventory_record.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.create_time
     *
     * @param createTime the value for sku_inventory_record.create_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_inventory_record.update_time
     *
     * @return the value of sku_inventory_record.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_inventory_record.update_time
     *
     * @param updateTime the value for sku_inventory_record.update_time
     *
     * @mbg.generated Thu Jun 19 11:34:39 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}