package com.yabobaozb.ecom.commodity.infra.model;

import java.math.BigDecimal;
import java.util.Date;

public class SkuInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.sku_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.name
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.sale_price
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.sale_status
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private Short saleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.remark
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.create_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_info.update_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.sku_id
     *
     * @return the value of sku_info.sku_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.sku_id
     *
     * @param skuId the value for sku_info.sku_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.name
     *
     * @return the value of sku_info.name
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.name
     *
     * @param name the value for sku_info.name
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.sale_price
     *
     * @return the value of sku_info.sale_price
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.sale_price
     *
     * @param salePrice the value for sku_info.sale_price
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.sale_status
     *
     * @return the value of sku_info.sale_status
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public Short getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.sale_status
     *
     * @param saleStatus the value for sku_info.sale_status
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setSaleStatus(Short saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.merchant_id
     *
     * @return the value of sku_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.merchant_id
     *
     * @param merchantId the value for sku_info.merchant_id
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.remark
     *
     * @return the value of sku_info.remark
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.remark
     *
     * @param remark the value for sku_info.remark
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.create_time
     *
     * @return the value of sku_info.create_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.create_time
     *
     * @param createTime the value for sku_info.create_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_info.update_time
     *
     * @return the value of sku_info.update_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_info.update_time
     *
     * @param updateTime the value for sku_info.update_time
     *
     * @mbg.generated Fri Jun 20 15:55:19 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}